# Generated by Django 4.2.13 on 2024-06-29 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institutesusermapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutes_user_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institute',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to='institutes.institute'),
        ),
        migrations.AddField(
            model_name='institute',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to='institutes.institute'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='institutes.institute'),
        ),
    ]
