# Generated by Django 4.2.13 on 2024-06-29 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
        ('batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbatchmapping',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_batch_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbatchmapping',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_user_batch_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbatchmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_batch_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchlectureplan',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_lecture_plans', to='batches.batch'),
        ),
        migrations.AddField(
            model_name='batchlectureplan',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_batch_lecture_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='institutes.institute'),
        ),
        migrations.AddField(
            model_name='batch',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
