# Generated by Django 4.2.13 on 2024-06-29 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('users', '0001_initial'),
        ('batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentrecordedrequest',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_recorded_requests', to='batches.batch'),
        ),
        migrations.AddField(
            model_name='studentrecordedrequest',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_student_recorded_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentrecordedrequest',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_recorded_requests', to='assignments.lecture'),
        ),
        migrations.AddField(
            model_name='recordedvideo',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_videos', to='batches.batch'),
        ),
        migrations.AddField(
            model_name='recordedvideo',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_videos', to='assignments.lecture'),
        ),
        migrations.AddField(
            model_name='library',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='batches.batch'),
        ),
        migrations.AddField(
            model_name='library',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='library',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecturetagmapping',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_tag_mappings', to='assignments.lecture'),
        ),
        migrations.AddField(
            model_name='lecturetagmapping',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_tag_mappings', to='assignments.tag'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lectures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='users.subject'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lectures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmenttagmapping',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmenttagmapping',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.tag'),
        ),
        migrations.AddField(
            model_name='assignmentquestiontagmapping',
            name='assignment_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignmentquestions'),
        ),
        migrations.AddField(
            model_name='assignmentquestiontagmapping',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.tag'),
        ),
        migrations.AddField(
            model_name='assignmentquestionsmetainfo',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentquestionsmetainfo',
            name='assignment_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignmentquestions'),
        ),
        migrations.AddField(
            model_name='assignmentquestionsmetainfo',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
        migrations.AddField(
            model_name='assignmentquestionoptions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignmentquestions'),
        ),
        migrations.AddField(
            model_name='assignmentmetainfo',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentmetainfo',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
        migrations.AddField(
            model_name='assignmentbatchmapping',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentbatchmapping',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
        migrations.AddField(
            model_name='assignmentattempts',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentattempts',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
        migrations.AddField(
            model_name='assignmentattempts',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignmentquestions'),
        ),
        migrations.AddField(
            model_name='assignmentattempts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subject'),
        ),
    ]
